name: Build abuseACL Windows Executable
on:
  workflow_dispatch: # This allows manual triggering
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install abuseacl and dependencies
        run: |
          python -m pip install --upgrade pip
          # Install explicit dependencies
          pip install -r requirements.txt
          # Install adidnsdump and its dependencies
          pip install -e .
          # Install PyInstaller
          pip install pyinstaller
          
      - name: Build executable
        run: |
          # Create a simple entry point script
          echo 'import sys; from abuseACL.__main__ import main; sys.exit(main())' > abuseacl_launcher.py
          # Use this entry script for PyInstaller
          pyinstaller --onefile --name abuseacl_windows_amd64.exe abuseacl_launcher.py
      
      - name: Create zip file
        run: |
          Compress-Archive -Path .\\dist\\abuseacl_windows_amd64.exe -DestinationPath abuseacl_windows.zip
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: abuseacl-windows
          path: abuseacl_windows.zip
